<a href="https://colab.research.google.com/github/uthours/Data-Processing-Visualization/blob/main/Quiz17.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Visualization 
#Grab the iris dataset. Answer the following questions:

In [22]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/nurfnick/Data_Viz/main/iris.csv')
df

     SepalLength  SepalWidth  PedalLength  PedalWidth           Class
0            5.1         3.5          1.4         0.2     Iris-setosa
1            4.9         3.0          1.4         0.2     Iris-setosa
2            4.7         3.2          1.3         0.2     Iris-setosa
3            4.6         3.1          1.5         0.2     Iris-setosa
4            5.0         3.6          1.4         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

[150 rows x 5 columns]

# 1. Does converting SepalLength to integer increase or decrease the mean?
Ans: Yes, converting SepalLength to integer decreases it's value.

# 2. Does the direction of the shift remain the same if you groupby Class?
Ans: Let's find out using shift function.

In [23]:
df_test=iris_df.shift()
df_test

     SepalLength  SepalWidth  PedalLength  PedalWidth           Class
0            NaN         NaN          NaN         NaN             NaN
1            5.1         3.5          1.4         0.2     Iris-setosa
2            4.9         3.0          1.4         0.2     Iris-setosa
3            4.7         3.2          1.3         0.2     Iris-setosa
4            4.6         3.1          1.5         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
145          6.7         3.3          5.7         2.5  Iris-virginica
146          6.7         3.0          5.2         2.3  Iris-virginica
147          6.3         2.5          5.0         1.9  Iris-virginica
148          6.5         3.0          5.2         2.0  Iris-virginica
149          6.2         3.4          5.4         2.3  Iris-virginica

[150 rows x 5 columns]

In [24]:
column= iris_df.groupby('Class') # applying shift after grouping them by class
column.shift()

     SepalLength  SepalWidth  PedalLength  PedalWidth
0            NaN         NaN          NaN         NaN
1            5.1         3.5          1.4         0.2
2            4.9         3.0          1.4         0.2
3            4.7         3.2          1.3         0.2
4            4.6         3.1          1.5         0.2
..           ...         ...          ...         ...
145          6.7         3.3          5.7         2.5
146          6.7         3.0          5.2         2.3
147          6.3         2.5          5.0         1.9
148          6.5         3.0          5.2         2.0
149          6.2         3.4          5.4         2.3

[150 rows x 4 columns]

Yes, direction of the shift remain the same if you groupby

# 3. Gather the mean, median, count and standard deviation of all columns when grouped by Class.

In [25]:
df.groupby('Class').SepalWidth.agg(['mean','median','count', 'std'])

                  mean  median  count       std
Class
Iris-setosa      3.418     3.4     50  0.381024
Iris-versicolor  2.770     2.8     50  0.313798
Iris-virginica   2.974     3.0     50  0.322497